Models/ActivityCreateModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel;

namespace dotNetBlainsBoredClient.Models
{
    public class ActivityCreateModel
    {

        public ActivityModel? Activity { get; set; }

        public List<string>? ActivityTypes { get; set; }

        public List<ActivityModel>? listActivities { get; set; }

    }
}

Models/ActivityModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Collections;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace dotNetBlainsBoredClient.Models
{
    [JsonObject]
    public class ActivityModel
    {
        //Description
        [Display(Name = "Description")]
        public string? activity { get; set; }

        //Accessibility rating
        [RegularExpression(@"[0-9]{0,}\.[0-9]{1}", ErrorMessage = "Enter a positive number value containing a single decimal.")]
        [Display(Name = "Accessibility rating")]
        public decimal? accessibility { get; set; }

        //Type
        [Display(Name = "Type")]
        [Required]
        public string? type { get; set; }

        //Number of participants
        [Display(Name = "Number of participants")]
        public int? participants { get; set; }

        //Relative price
        [Display(Name = "Relative price")]
        public decimal? price { get; set; }

        public string? key { get; set; }

        public string? error { get; set; }

    }
}

Models/ErrorViewModel.cs
namespace dotNetBlainsBoredClient.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ActivityController.cs
using dotNetBlainsBoredClient.Models;
using Microsoft.AspNetCore.Connections;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.WebUtilities;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Diagnostics;
using System.Net.Http.Headers;

namespace dotNetBlainsBoredClient.Controllers
{
    public class ActivityController : Controller
    {

        private readonly ILogger<ActivityController> _logger;

        public ActivityController(ILogger<ActivityController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            string baseEndpoint = "https://www.boredapi.com/api/activity/";
            List<ActivityModel>? listActivities = new List<ActivityModel>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseEndpoint);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage resActivities = await client.GetAsync(baseEndpoint);
                if (resActivities.IsSuccessStatusCode)
                {
                    listActivities = JsonConvert.DeserializeObject<List<ActivityModel>>("[" + resActivities.Content.ReadAsStringAsync().Result + "]");
                }
                return View(listActivities);
            }
        }

        public async Task<ActionResult> Create(ActivityCreateModel queryActivity)
        {      
            // Create model
            ActivityCreateModel viewModel = new ActivityCreateModel();
             
                // Load select list items for activity types
                viewModel.Activity = new ActivityModel();
                viewModel.ActivityTypes = new List<string>()
                    {
                        "busywork",
                        "charity",
                        "cooking", 
                        "diy",
                        "education",
                        "music",
                        "recreational",
                        "relaxation",
                        "social"
                    };

                // Check for null
                if (queryActivity.Activity != null)
                {

                    // Validation after submit
                    if (!ModelState.IsValid)
                    {
                        return View(viewModel);
                    }
                    
                    // Api call
                    const string url = "https://www.boredapi.com/api/activity";
                    Dictionary<string, string> queryString = new Dictionary<string, string>() {
                        { "type", queryActivity.Activity.type },
                        { "participants", queryActivity.Activity.participants.ToString() },
                        { "price", queryActivity.Activity.price.ToString() },
                        { "accessibility", queryActivity.Activity.accessibility.ToString() }
                    };
                    Uri urlEndpoint = new Uri(QueryHelpers.AddQueryString(url, queryString));

                    using (var client = new HttpClient())
                    {
                        client.BaseAddress = urlEndpoint;
                        client.DefaultRequestHeaders.Clear();
                        client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                        HttpResponseMessage resActivities = await client.GetAsync(urlEndpoint);
                        if (resActivities.IsSuccessStatusCode)
                        {
                            List<ActivityModel>? listActivities = JsonConvert.DeserializeObject<List<ActivityModel>>("[" + resActivities.Content.ReadAsStringAsync().Result + "]");
                            if (listActivities.Any())
                            {
                                List<ActivityModel> currentlistActivities = new List<ActivityModel>();
                                foreach (var activity in listActivities)
                                {
                                    currentlistActivities.Add(activity);
                                }
                                viewModel.listActivities = currentlistActivities;
                            }
                        }
                    }

                }
            return View(viewModel);            
        }

    }
}

Controllers/HomeController.cs
using dotNetBlainsBoredClient.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace dotNetBlainsBoredClient.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Activity/Create.cshtml
@model dotNetBlainsBoredClient.Models.ActivityCreateModel

@{
    ViewData["Title"] = "Query";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>View</title>
</head>
<body>

    <h4>Let's find something to do!</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" method="POST">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Activity.type" class="control-label"></label><br />
                    <select asp-items="@(new SelectList(Model.ActivityTypes))" class="form-control" asp-for="Activity.type">
                            <option value="">Please select...</option>
                    </select>
                    <span asp-validation-for="Activity.type" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Activity.participants" class="control-label"></label>
                    <input type="number" asp-for="Activity.participants" class="form-control" placeholder="number of participants" />
                    <span asp-validation-for="Activity.participants" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Activity.price" class="control-label"></label>
                    <input type="number" asp-for="Activity.price" class="form-control" placeholder="(enter 0 for free) to expensive" />
                    <span asp-validation-for="Activity.price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Activity.accessibility" class="control-label"></label>
                    <input asp-for="Activity.accessibility" class="form-control" placeholder="most to least (enter 0 for least)"/>
                    <span asp-validation-for="Activity.accessibility" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Go!" class="btn btn-primary" style="margin-top: 20px"/>
                </div>
            </form>
        </div>
    </div>

    <table class="table">
        @if (Model.listActivities != null)
        {
            <thead>
                <tr>
                    <th>Description</th>
                    <th></th>
                    <th>Type</th>
                    <th></th>
                    <th>Number of participants</th>
                    <th></th>
                    <th>Relative price</th>
                    <th></th>
                    <th>Accessibility rating</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var activity in Model.listActivities)
                {
                    <tr>
                        <td>@activity.activity</td>
                        <td></td>
                        <td>@activity.type</td>
                        <td></td>
                        <td>@activity.participants</td>
                        <td></td>
                        <td>@activity.price</td>
                        <td></td>
                        <td>@activity.accessibility</td>
                    </tr>
                }
            </tbody>
        } 
    </table>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

Views/Activity/Index.cshtml
@model IEnumerable<dotNetBlainsBoredClient.Models.ActivityModel>

@{
    ViewData["Title"] = "Random Fun Thing";
}

<h1>Random Fun Thing!</h1>

<a asp-area="" asp-controller="Activity" asp-action="Index" class="btn btn-primary">Go!</a>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.activity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.accessibility)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.participants)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.key)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.activity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.accessibility)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.participants)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.key)
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">I'm Bored</h1>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - dotNetBlainsBoredClient</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/dotNetBlainsBoredClient.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">dotNetBlainsBoredClient</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>d
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Activity" asp-action="Index">Lazy Picker</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Activity" asp-action="Create">Pick Me</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - dotNetBlainsBoredClient 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>